-- ============================================================
-- JOB TRACKER SCHEMA
-- Run this in Vercel Postgres query console
-- ============================================================

CREATE TABLE IF NOT EXISTS companies (
  id         SERIAL PRIMARY KEY,
  name       VARCHAR(255) NOT NULL,
  url        VARCHAR(500),
  careers_url VARCHAR(500),
  tier       INTEGER DEFAULT 3,
  tag        TEXT,
  sort_order INTEGER DEFAULT 999,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS jobs (
  id            SERIAL PRIMARY KEY,
  company_id    INTEGER REFERENCES companies(id) ON DELETE CASCADE,
  title         VARCHAR(500),
  url           VARCHAR(1000),
  status        VARCHAR(50) DEFAULT 'new',
  notes         TEXT,
  salary_range  VARCHAR(255),
  match_quality VARCHAR(100),
  date_applied  DATE,
  created_at    TIMESTAMP DEFAULT NOW(),
  updated_at    TIMESTAMP DEFAULT NOW()
);

-- ============================================================
-- SEED: 180 TARGET COMPANIES
-- ============================================================

INSERT INTO companies (name, url, careers_url, tier, tag, sort_order) VALUES
-- TIER 1: DREAM FIT
('Vercel', 'https://vercel.com', 'https://vercel.com/careers', 1, 'Next.js creators, frontend infra, design-obsessed', 1),
('Linear', 'https://linear.app', 'https://linear.app/careers', 1, 'Best-in-class design, productivity tools, remote-first', 2),
('Framer', 'https://framer.com', 'https://framer.com/careers', 1, 'Design+code overlap, component-driven, design engineer heaven', 3),
('Raycast', 'https://raycast.com', 'https://raycast.com/careers', 1, 'Design-obsessed developer tools, tiny elite team', 4),
('Tailwind Labs', 'https://tailwindcss.com', 'https://tailwindcss.com/careers', 1, 'CSS framework creators, design systems at the language level', 5),
('WorkOS', 'https://workos.com', 'https://workos.com/careers', 1, 'Radix UI creators, design systems, developer tools', 6),
('Cursor', 'https://cursor.com', 'https://cursor.com/careers', 1, 'AI code editor, engineering craft, design quality matters', 7),
('Codeium', 'https://codeium.com', 'https://codeium.com/careers', 1, 'AI dev tools, fast-growing, engineers who care about UX', 8),
('Liveblocks', 'https://liveblocks.io', 'https://liveblocks.io/careers', 1, 'Real-time collaboration primitives, dev tools', 9),
('Chromatic', 'https://www.chromatic.com', 'https://www.chromatic.com/careers', 1, 'Storybook/UI testing, component library culture, design systems', 10),
('PostHog', 'https://posthog.com', 'https://posthog.com/careers', 1, 'Fully remote, open source, ships fast', 11),
('Sanity', 'https://sanity.io', 'https://sanity.io/careers', 1, 'Headless CMS, content infrastructure, component architecture', 12),
('Supabase', 'https://supabase.com', 'https://supabase.com/careers', 1, 'Open source Firebase alt, strong developer tools culture', 13),
('Clerk', 'https://clerk.com', 'https://clerk.com/careers', 1, 'Auth developer tools, React/TypeScript, design-forward docs', 14),
('Resend', 'https://resend.com', 'https://resend.com/careers', 1, 'Email dev tools, React Email creator, small team', 15),
('Expo', 'https://expo.dev', 'https://expo.dev/careers', 1, 'React Native tooling, cross-platform, open source', 16),
('Prisma', 'https://prisma.io', 'https://prisma.io/careers', 1, 'TypeScript-first ORM, developer tools', 17),
('Convex', 'https://convex.dev', 'https://convex.dev/careers', 1, 'Real-time database, developer tools, TypeScript-first', 18),
('Railway', 'https://railway.app', 'https://railway.app/careers', 1, 'Deployment platform, strong design aesthetic, small team', 19),
('Fly.io', 'https://fly.io', 'https://fly.io/jobs', 1, 'Edge deployment, quirky culture, developer-first', 20),
('Deno', 'https://deno.com', 'https://deno.com/careers', 1, 'JS runtime creators, TypeScript native', 21),
('Cal.com', 'https://cal.com', 'https://cal.com/careers', 1, 'Open source scheduling, great design, fully distributed', 22),
('Stytch', 'https://stytch.com', 'https://stytch.com/careers', 1, 'Auth developer tools, React-heavy, design systems', 23),
('PlanetScale', 'https://planetscale.com', 'https://planetscale.com/careers', 1, 'Database platform, great design culture', 24),
('Nx / Nrwl', 'https://nx.dev', 'https://nx.dev/company/careers', 1, 'Monorepo tooling, direct match for PMX module federation work', 25),
('StackBlitz', 'https://stackblitz.com', 'https://stackblitz.com/careers', 1, 'Browser-based dev environment, web container technology', 26),
('CodeSandbox', 'https://codesandbox.io', 'https://codesandbox.io/careers', 1, 'Cloud dev environments, React-first', 27),
('Zed Industries', 'https://zed.dev', 'https://zed.dev/jobs', 1, 'Next-gen code editor, performance-obsessed, small team', 28),
('Warp', 'https://warp.dev', 'https://warp.dev/careers', 1, 'Terminal reimagined, developer UX obsession', 29),
('Mintlify', 'https://mintlify.com', 'https://mintlify.com/careers', 1, 'Docs-as-code platform, React component library', 30),
('ReadMe', 'https://readme.com', 'https://readme.com/careers', 1, 'API docs platform, developer experience focus', 31),
('Lottiefiles', 'https://lottiefiles.com', 'https://lottiefiles.com/careers', 1, 'Animation platform, design+dev overlap, Visual Comm degree gold', 32),
('Neon', 'https://neon.tech', 'https://neon.tech/careers', 1, 'Serverless Postgres, dev tools culture', 33),
('Sourcegraph', 'https://sourcegraph.com', 'https://boards.greenhouse.io/sourcegraph', 1, 'Code intelligence, AI-powered dev tools', 34),
('Temporal', 'https://temporal.io', 'https://temporal.io/careers', 1, 'Workflow engine, dev tools, TypeScript SDK', 35),
('Inngest', 'https://inngest.com', 'https://inngest.com/careers', 1, 'Background jobs platform, DX-focused, TypeScript-first', 36),
('Trigger.dev', 'https://trigger.dev', 'https://trigger.dev/careers', 1, 'Background jobs for devs, open source, TypeScript', 37),
('Novu', 'https://novu.co', 'https://novu.co/careers', 1, 'Notification infrastructure, open source, developer tools', 38),
('Gitpod', 'https://gitpod.io', 'https://gitpod.io/careers', 1, 'Cloud dev environments, open source, developer experience', 39),
('Zeplin', 'https://zeplin.io', 'https://zeplin.io/careers', 1, 'Design handoff tool, lives at design/dev intersection', 40),
('Depot', 'https://depot.dev', 'https://depot.dev/careers', 1, 'Faster container builds, dev tools, TypeScript', 41),
('Upstash', 'https://upstash.com', 'https://upstash.com/careers', 1, 'Serverless Redis/Kafka, dev tools, strong React integration', 42),
-- TIER 2: HIGH PRIORITY
('Notion', 'https://notion.so', 'https://notion.so/careers', 2, 'Design-forward productivity, React-heavy frontend', 43),
('Figma', 'https://figma.com', 'https://figma.com/careers', 2, 'Design tool, design+code culture, TypeScript', 44),
('Pitch', 'https://pitch.com', 'https://pitch.com/careers', 2, 'Presentation tool, design-obsessed, remote-friendly', 45),
('Webflow', 'https://webflow.com', 'https://webflow.com/careers', 2, 'No-code/design tool, visual communication degree relevant', 46),
('Ghost', 'https://ghost.org', 'https://careers.ghost.org', 2, 'Open source publishing, fully remote, strong design', 47),
('Coda', 'https://coda.io', 'https://coda.io/jobs', 2, 'Docs+spreadsheets hybrid, strong frontend culture', 48),
('Dovetail', 'https://dovetail.com', 'https://dovetail.com/careers', 2, 'User research tools, design-forward, React/TypeScript', 49),
('Maze', 'https://maze.co', 'https://maze.co/careers', 2, 'Design research platform, design+code culture', 50),
('Loom', 'https://loom.com', 'https://loom.com/careers', 2, 'Video messaging, strong frontend, Atlassian-owned', 51),
('Miro', 'https://miro.com', 'https://miro.com/careers', 2, 'Visual collaboration, React-heavy, strong design', 52),
('Airtable', 'https://airtable.com', 'https://airtable.com/careers', 2, 'No-code database, strong frontend, design-forward', 53),
('LaunchDarkly', 'https://launchdarkly.com', 'https://launchdarkly.com/careers', 2, 'Feature flags, developer tools, React SDK', 54),
('Sentry', 'https://sentry.io', 'https://sentry.io/careers', 2, 'Error monitoring, open source, frontend-heavy', 55),
('LogRocket', 'https://logrocket.com', 'https://logrocket.com/careers', 2, 'Session replay/monitoring, lives in frontend world', 56),
('FullStory', 'https://fullstory.com', 'https://fullstory.com/careers', 2, 'Digital experience analytics, frontend instrumentation', 57),
('Hotjar', 'https://hotjar.com', 'https://hotjar.com/careers', 2, 'Heatmaps/UX tools, fully remote, strong design', 58),
('Amplitude', 'https://amplitude.com', 'https://amplitude.com/careers', 2, 'Product analytics, remote-friendly, React-heavy', 59),
('Algolia', 'https://algolia.com', 'https://algolia.com/careers', 2, 'Search platform, great DX, strong React/TypeScript SDK', 60),
('Storyblok', 'https://storyblok.com', 'https://storyblok.com/careers', 2, 'Headless CMS, visual editor, component library', 61),
('Contentful', 'https://contentful.com', 'https://contentful.com/careers', 2, 'Headless CMS, strong frontend, component-driven', 62),
('Netlify', 'https://netlify.com', 'https://netlify.com/careers', 2, 'Frontend deployment, DX-focused, remote-first', 63),
('Stripe', 'https://stripe.com', 'https://stripe.com/jobs', 2, 'Payments, legendary docs/design quality, high bar', 64),
('Brex', 'https://brex.com', 'https://brex.com/careers', 2, 'Fintech, design-forward, strong React/TypeScript', 65),
('Plaid', 'https://plaid.com', 'https://plaid.com/careers', 2, 'Fintech dev tools, developer experience, remote-friendly', 66),
('Paddle', 'https://paddle.com', 'https://paddle.com/careers', 2, 'Payments platform, fully remote, strong frontend', 67),
('Lemon Squeezy', 'https://lemonsqueezy.com', 'https://lemonsqueezy.com/careers', 2, 'Payments for devs, beautiful design, small team', 68),
('Appsmith', 'https://appsmith.com', 'https://appsmith.com/careers', 2, 'Open source low-code, component library, React', 69),
('Height', 'https://height.app', 'https://height.app/careers', 2, 'Project management, design-obsessed, tiny team', 70),
('Perplexity', 'https://perplexity.ai', 'https://perplexity.ai/careers', 2, 'AI search, fast-growing, strong frontend investment', 71),
('Hugging Face', 'https://huggingface.co', 'https://huggingface.co/jobs', 2, 'AI/ML platform, open source, React-heavy', 72),
('Weights & Biases', 'https://wandb.ai', 'https://wandb.ai/site/company/careers', 2, 'ML tooling, dev tools culture, strong frontend', 73),
('Replicate', 'https://replicate.com', 'https://replicate.com/careers', 2, 'AI model platform, design-forward, developer tools', 74),
('Grafana Labs', 'https://grafana.com', 'https://grafana.com/about/careers', 2, 'Open source observability, fully remote, frontend dashboards', 75),
('Infisical', 'https://infisical.com', 'https://infisical.com/careers', 2, 'Secrets management, open source, TypeScript, small team', 76),
('Budibase', 'https://budibase.com', 'https://budibase.com/careers', 2, 'Open source low-code, component builder, remote', 77),
('Chargebee', 'https://chargebee.com', 'https://chargebee.com/careers', 2, 'Subscription billing, design-forward, React/TypeScript', 78),
('Retool', 'https://retool.com', 'https://retool.com/careers', 2, 'Internal tools, component library, React', 79),
('Runway', 'https://runwayml.com', 'https://runwayml.com/careers', 2, 'AI video, design+engineering intersection, creative tools', 80),
-- TIER 3: STRONG FIT
('GitLab', 'https://gitlab.com', 'https://about.gitlab.com/jobs', 3, 'Fully remote pioneer, DevOps platform', 81),
('Zapier', 'https://zapier.com', 'https://zapier.com/careers', 3, 'Automation platform, remote-first, strong frontend', 82),
('HubSpot', 'https://hubspot.com', 'https://hubspot.com/careers', 3, 'Marketing software, remote-friendly, solid frontend', 83),
('Intercom', 'https://intercom.com', 'https://intercom.com/careers', 3, 'Customer messaging, design-forward, remote-friendly', 84),
('Grammarly', 'https://grammarly.com', 'https://grammarly.com/jobs', 3, 'AI writing tools, strong frontend, design matters', 85),
('Duolingo', 'https://duolingo.com', 'https://careers.duolingo.com', 3, 'Ed tech, design-obsessed, remote-friendly', 86),
('Discord', 'https://discord.com', 'https://discord.com/careers', 3, 'Communication platform, React-heavy, strong engineering', 87),
('Canva', 'https://canva.com', 'https://canva.com/careers', 3, 'Design tools, visual communication relevant, remote', 88),
('Spotify', 'https://spotify.com', 'https://lifeatspotify.com', 3, 'Audio streaming, remote-friendly, design system culture', 89),
('Pinterest', 'https://pinterest.com', 'https://careers.pinterest.com', 3, 'Visual discovery, remote-friendly, design-forward', 90),
('Cloudflare', 'https://cloudflare.com', 'https://cloudflare.com/careers', 3, 'Internet infrastructure, remote-friendly, Workers growing', 91),
('Datadog', 'https://datadoghq.com', 'https://careers.datadoghq.com', 3, 'Monitoring/observability, frontend-heavy dashboards', 92),
('PagerDuty', 'https://pagerduty.com', 'https://pagerduty.com/careers', 3, 'Incident management, remote-friendly, solid frontend', 93),
('HashiCorp', 'https://hashicorp.com', 'https://hashicorp.com/careers', 3, 'Infrastructure tools, fully remote, docs and UX matter', 94),
('Elastic', 'https://elastic.co', 'https://elastic.co/careers', 3, 'Search platform, distributed remote, frontend dashboards', 95),
('New Relic', 'https://newrelic.com', 'https://newrelic.com/about/careers', 3, 'Observability, remote-friendly, frontend-heavy', 96),
('Render', 'https://render.com', 'https://render.com/careers', 3, 'Cloud hosting, design-forward, small team', 97),
('DigitalOcean', 'https://digitalocean.com', 'https://digitalocean.com/careers', 3, 'Cloud platform, remote-friendly, developer-first', 98),
('Twilio', 'https://twilio.com', 'https://twilio.com/en-us/company/jobs', 3, 'Communications platform, remote-friendly', 99),
('Okta', 'https://okta.com', 'https://okta.com/company/careers', 3, 'Identity platform, remote-friendly, frontend SDK', 100),
('Help Scout', 'https://helpscout.com', 'https://helpscout.com/company/careers', 3, 'Customer support, fully remote, strong culture', 101),
('Front', 'https://front.com', 'https://front.com/company/careers', 3, 'Customer ops platform, remote-friendly, React-heavy', 102),
('Doist', 'https://doist.com', 'https://doist.com/careers', 3, 'Todoist creators, 100% remote, async culture', 103),
('Buffer', 'https://buffer.com', 'https://buffer.com/journey', 3, 'Social media tools, fully remote, transparent culture', 104),
('Automattic', 'https://automattic.com', 'https://automattic.com/work-with-us', 3, 'WordPress.com, fully distributed, React Gutenberg', 105),
('Basecamp', 'https://basecamp.com', 'https://basecamp.com/jobs', 3, 'Project management, fully remote, remote work pioneers', 106),
('Atlassian', 'https://atlassian.com', 'https://www.atlassian.com/company/careers', 3, 'Dev tools, Jira/Confluence, remote-friendly, design system', 107),
('Asana', 'https://asana.com', 'https://asana.com/jobs', 3, 'Work management, remote-friendly, strong frontend', 108),
('Monday.com', 'https://monday.com', 'https://monday.com/careers', 3, 'Work OS, remote-friendly, React-heavy', 109),
('Lattice', 'https://lattice.com', 'https://lattice.com/careers', 3, 'HR software, remote-friendly, React/TypeScript', 110),
('Rippling', 'https://rippling.com', 'https://rippling.com/careers', 3, 'HR/IT platform, remote-friendly, React-heavy', 111),
('Deel', 'https://deel.com', 'https://deel.com/careers', 3, 'Global HR/payroll, fully remote team', 112),
('Remote', 'https://remote.com', 'https://remote.com/careers', 3, 'Remote HR platform, fully remote, strong culture', 113),
('Gusto', 'https://gusto.com', 'https://gusto.com/about/careers', 3, 'Payroll/HR, remote-friendly, strong frontend', 114),
('Typeform', 'https://typeform.com', 'https://typeform.com/careers', 3, 'Forms platform, design-obsessed, remote-friendly', 115),
('Segment', 'https://segment.com', 'https://segment.com/careers', 3, 'Data infrastructure, developer tools culture', 116),
('Heap', 'https://heap.io', 'https://heap.io/company/careers', 3, 'Product analytics, frontend instrumentation', 117),
('Pendo', 'https://pendo.io', 'https://pendo.io/careers', 3, 'Product analytics, in-app guidance, frontend-heavy', 118),
('UserTesting', 'https://usertesting.com', 'https://usertesting.com/company/careers', 3, 'UX research platform, design+dev overlap', 119),
('ClickUp', 'https://clickup.com', 'https://clickup.com/careers', 3, 'Productivity platform, remote-friendly, React-heavy', 120),
('Aha!', 'https://aha.io', 'https://aha.io/company/careers', 3, 'Product roadmaps, fully remote, design-forward', 121),
('Shortcut', 'https://shortcut.com', 'https://shortcut.com/company/jobs', 3, 'Project management, remote-friendly, design-forward', 122),
('OpenAI', 'https://openai.com', 'https://openai.com/careers', 3, 'AI company, strong frontend for ChatGPT/API, high comp', 123),
('Anthropic', 'https://anthropic.com', 'https://anthropic.com/careers', 3, 'AI safety, Claude creator, strong frontend for Claude.ai', 124),
('Cohere', 'https://cohere.com', 'https://cohere.com/careers', 3, 'Enterprise AI, developer tools, growing frontend', 125),
('Together AI', 'https://together.ai', 'https://together.ai/careers', 3, 'AI inference platform, developer tools, fast-growing', 126),
('Scale AI', 'https://scale.com', 'https://scale.com/careers', 3, 'AI data platform, frontend-heavy tooling, high comp', 127),
('Jasper', 'https://jasper.ai', 'https://jasper.ai/careers', 3, 'AI writing, design-forward, React/TypeScript', 128),
('Mixpanel', 'https://mixpanel.com', 'https://mixpanel.com/careers', 3, 'Product analytics, remote-friendly, strong frontend', 129),
('Calendly', 'https://calendly.com', 'https://careers.calendly.com', 3, 'Scheduling platform, remote-friendly, React/TypeScript', 130),
-- TIER 4: WORTH APPLYING
('Shopify', 'https://shopify.com', 'https://shopify.com/careers', 4, 'E-commerce, remote-friendly, Polaris design system, Liquid', 131),
('Dropbox', 'https://dropbox.com', 'https://dropbox.com/jobs', 4, 'Cloud storage, remote-friendly, strong design culture', 132),
('Airbnb', 'https://airbnb.com', 'https://careers.airbnb.com', 4, 'Travel, strong frontend/design culture', 133),
('Reddit', 'https://reddit.com', 'https://www.redditinc.com/careers', 4, 'Community platform, remote-friendly, major frontend rebuild', 134),
('Twitch', 'https://twitch.tv', 'https://twitch.tv/jobs', 4, 'Streaming, Amazon-owned, remote-friendly', 135),
('Snap', 'https://snap.com', 'https://snap.com/en-US/jobs', 4, 'Social media, remote-friendly, design-forward', 136),
('Block', 'https://block.xyz', 'https://careers.block.xyz', 4, 'Fintech, Square/Cash App, remote-friendly', 137),
('Coinbase', 'https://coinbase.com', 'https://coinbase.com/careers', 4, 'Crypto exchange, remote-friendly, strong frontend', 138),
('Instacart', 'https://instacart.com', 'https://instacart.com/careers', 4, 'Grocery delivery, remote-friendly, strong frontend', 139),
('Robinhood', 'https://robinhood.com', 'https://careers.robinhood.com', 4, 'Fintech, remote-friendly, design-forward trading app', 140),
('Klarna', 'https://klarna.com', 'https://klarna.com/careers', 4, 'BNPL/fintech, design-forward, remote-friendly', 141),
('Affirm', 'https://affirm.com', 'https://affirm.com/careers', 4, 'BNPL/fintech, remote-friendly, React-heavy', 142),
('Zoom', 'https://zoom.us', 'https://careers.zoom.us', 4, 'Video comms, remote-friendly, large engineering org', 143),
('Box', 'https://box.com', 'https://box.com/careers', 4, 'Cloud content management, remote-friendly', 144),
('GitHub', 'https://github.com', 'https://github.com/about/careers', 4, 'Microsoft-owned, developer tools, remote-friendly', 145),
('Salesforce', 'https://salesforce.com', 'https://salesforce.com/careers', 4, 'CRM, remote-friendly, Lightning design system', 146),
('Adobe', 'https://adobe.com', 'https://adobe.com/careers', 4, 'Creative software, design-focused, Spectrum design system', 147),
('Zendesk', 'https://zendesk.com', 'https://jobs.zendesk.com', 4, 'Customer service, remote-friendly, strong frontend', 148),
('Freshworks', 'https://freshworks.com', 'https://careers.freshworks.com', 4, 'CRM/support, remote-friendly, growing frontend', 149),
('Chime', 'https://chime.com', 'https://careers.chime.com', 4, 'Neobank, remote-friendly, design-forward, strong frontend', 150),
('DoorDash', 'https://doordash.com', 'https://careers.doordash.com', 4, 'Delivery, remote-friendly, large engineering org', 151),
('Lyft', 'https://lyft.com', 'https://lyft.com/careers', 4, 'Rideshare, remote-friendly, design system culture', 152),
('Qualtrics', 'https://qualtrics.com', 'https://qualtrics.com/careers', 4, 'Experience management, remote-friendly, React-heavy', 153),
('SurveyMonkey', 'https://surveymonkey.com', 'https://careers.surveymonkey.com', 4, 'Forms/surveys, remote-friendly, strong frontend', 154),
('Mailchimp', 'https://mailchimp.com', 'https://mailchimp.com/careers', 4, 'Email marketing, Intuit-owned, strong design system', 155),
('Zenefits', 'https://zenefits.com', 'https://zenefits.com/careers', 4, 'HR platform, remote-friendly, React-heavy', 156),
('Splunk', 'https://splunk.com', 'https://careers.splunk.com', 4, 'Data observability, Cisco-owned, remote-friendly', 157),
('1Password', 'https://1password.com', 'https://1password.com/careers', 4, 'Password manager, design-forward, remote-friendly', 158),
('Fingerprint', 'https://fingerprint.com', 'https://fingerprint.com/careers', 4, 'Device identity, open source, marketing engineering', 159),
('Euclid Power', 'https://euclidpower.com', 'https://euclidpower.com/careers', 4, 'Renewable energy SaaS, remote-first, staff frontend', 160),
-- TIER 5: BIG BRAND
('Microsoft', 'https://microsoft.com', 'https://careers.microsoft.com', 5, 'GitHub, VS Code, Azure, TypeScript creators', 161),
('Google', 'https://google.com', 'https://careers.google.com', 5, 'Search/cloud, Material Design, top-tier frontend', 162),
('Meta', 'https://meta.com', 'https://metacareers.com', 5, 'React/React Native creators, open source, design systems', 163),
('Apple', 'https://apple.com', 'https://jobs.apple.com', 5, 'Design-obsessed culture, web frontend roles', 164),
('Amazon', 'https://amazon.com', 'https://amazon.jobs', 5, 'AWS Console, Cloudscape design system', 165),
('Netflix', 'https://netflix.com', 'https://jobs.netflix.com', 5, 'Streaming, high comp ($300K+), design systems', 166),
('LinkedIn', 'https://linkedin.com', 'https://careers.linkedin.com', 5, 'Microsoft-owned, professional network, strong frontend', 167),
('Uber', 'https://uber.com', 'https://uber.com/careers', 5, 'Rides/delivery, Base Web design system', 168),
('PayPal', 'https://paypal.com', 'https://careers.pypl.com', 5, 'Payments, large frontend engineering org', 169),
('Intuit', 'https://intuit.com', 'https://careers.intuit.com', 5, 'TurboTax/QuickBooks, Harmony design system', 170),
('Workday', 'https://workday.com', 'https://careers.workday.com', 5, 'HR software, large frontend org', 171),
('ServiceNow', 'https://servicenow.com', 'https://careers.servicenow.com', 5, 'Enterprise IT, large scale React frontend', 172),
('IBM', 'https://ibm.com', 'https://ibm.com/careers', 5, 'Carbon Design System creators, remote-friendly', 173),
('Palo Alto Networks', 'https://paloaltonetworks.com', 'https://careers.paloaltonetworks.com', 5, 'Cybersecurity, large frontend engineering org', 174),
('CrowdStrike', 'https://crowdstrike.com', 'https://crowdstrike.com/careers', 5, 'Cybersecurity, React-heavy dashboards', 175),
('Snowflake', 'https://snowflake.com', 'https://careers.snowflake.com', 5, 'Data cloud, strong frontend engineering', 176),
('Databricks', 'https://databricks.com', 'https://databricks.com/company/careers', 5, 'Data/AI platform, complex frontend', 177),
('Palantir', 'https://palantir.com', 'https://palantir.com/careers', 5, 'Data analytics, complex UI, design systems at scale', 178),
('NVIDIA', 'https://nvidia.com', 'https://nvidia.com/careers', 5, 'AI/GPU leader, web products team, exceptional comp', 179),
('Ramp', 'https://ramp.com', 'https://ramp.com/careers', 5, 'Fintech, Design Engineer role, financial ops platform', 180);

-- ============================================================
-- SEED: REAL APPLICATIONS FROM JOB-LOG.JSON
-- Uses WITH clause to look up company IDs by name
-- ============================================================

WITH co AS (SELECT id, name FROM companies)
INSERT INTO jobs (company_id, title, status, salary_range, match_quality, date_applied, notes)
SELECT c.id, j.title, j.status, j.salary, j.match, j.applied::DATE, j.notes
FROM co c
JOIN (VALUES
  ('NBCUniversal',          'Sr. Design Engineer',                          'new',       '$150,000 - $195,000',       'PERFECT',     '2025-01-12', 'Design + engineering hybrid. AI-forward. Perfect tech stack.'),
  ('Stripe',                'Design Engineer, Expansion',                   'submitted', '$146,400 - $219,600',       'GOOD',        '2025-01-13', 'Already applied. Design Engineer role.'),
  ('ClickUp',               'Senior UI Design Engineer',                    'new',       '$160,000 - $210,000',       'PERFECT',     '2025-01-13', 'DREAM MATCH! They mention Cursor/AI tooling specifically.'),
  ('WorkOS',                'Software Engineer - Frontend',                 'submitted', '$175,000 - $250,000',       'GOOD',        '2025-01-13', 'Radix UI builders. Design systems focus.'),
  ('Figma',                 'Software Engineer, Web Platform',              'new',       '$149,000 - $350,000',       'GOOD',        '2025-01-13', 'Code Platform team. Design to code translation.'),
  ('Microsoft',             'Senior Software Engineer (Azure Portal)',      'submitted', '$119,800 - $258,000',       'GOOD',        '2025-01-23', 'Azure Portal frontend. Framework/SDK development.'),
  ('Zapier',                'Frontend Engineer, Sr. (UX Engineer)',         'new',       'Not listed (~$150-220K)',   'GOOD',        '2025-01-26', 'UX Engineer + Copilot team. Visual Communication degree matters!'),
  ('Webflow',               'Senior Software Engineer, Webflow Cloud',      'new',       '$150,100 - $207,100',       'GOOD',        '2025-01-26', 'Full-stack with frontend focus. React/TypeScript/Node.js.'),
  ('Bubble',                'Senior Software Engineer, Core DX',            'new',       '$183,000 - $237,000',       'GOOD',        '2025-01-26', 'PERFECT MATCH for PMX developer tooling work!'),
  ('Vanta',                 'Senior Software Engineer, Frontend Platform',  'submitted', '$179,000 - $211,000',       'EXCELLENT',   '2025-01-26', 'Frontend Platform = PMX developer tooling at scale.'),
  ('Ramp',                  'Senior Design-Engineer, Design Systems',       'new',       '$159,100 - $218,800',       'EXCELLENT',   '2025-01-27', 'UNICORN ROLE: Designer who codes.'),
  ('Vanta',                 'Senior Software Engineer, Design Systems',     'new',       'No salary listed',          'EXCELLENT',   '2025-01-27', 'Second Vanta role. Design Systems team. Better fit.'),
  ('Cloudflare',            'Senior Frontend Engineer, Dashboard Exp',      'new',       '$168,000 - $254,000',       'EXCELLENT',   '2025-01-27', 'Module Federation experience is a HUGE plus.'),
  ('Customer.io',           'Senior Frontend Product Engineer',             'new',       '$150,000 - $200,000',       'GOOD',        '2025-01-27', 'Pure frontend product engineer. Design systems focus.'),
  ('Slack / Salesforce',    'Senior Software Engineer, Frontend',           'submitted', '$143,300 - $306,600',       'GOOD',        '2025-01-27', 'Frontend DevXP team at Slack. PMX work at scale.'),
  ('Slack / Salesforce',    'Staff Software Engineer, Frontend Infra',      'submitted', '$197,300 - $313,700',       'EXCELLENT',   '2025-02-04', 'STAFF level. In Consideration status. Module Federation!'),
  ('Veeam Software',        'Frontend Developer, VDC',                      'interested','$198,100 - $367,900',       'EXCELLENT',   '2025-01-27', 'INTERVIEW INVITATION RECEIVED! Phone screen scheduled.'),
  ('Veeam Software',        'Frontend Developer, Data Intelligence',        'submitted', '$198,100 - $367,900',       'EXCELLENT',   '2025-01-27', 'Second Veeam role. Same exceptional salary range.'),
  ('B-Stock Solutions',     'Senior Frontend Engineer, React & Next.js',    'submitted', '$145,000 - $175,000',       'EXCELLENT',   '2025-01-28', 'React 18+, Next.js 15+. Technical leadership role.'),
  ('Consensys',             'Senior UX Engineer',                           'new',       '$149,000 - $210,000',       'EXCELLENT',   '2025-01-28', 'MetaMask (30M+ users). UX Engineer bridging design and engineering.'),
  ('Tapcart',               'Senior Fullstack Engineer, Content Exp',       'new',       '$175,000 - $200,000',       'EXCELLENT',   '2025-01-28', 'Component library and UI blocks. Shopify platform.'),
  ('Vercel',                'Forward-Deployed Engineer',                    'submitted', '$137,000 - $207,000',       'EXCELLENT',   '2026-02-19', 'Next.js migrations, code audits, AI SDK. 25-40% travel.'),
  ('Reddit',                'Senior Web Engineer, Web Platform',            'submitted', '$190,800 - $267,100',       'EXCELLENT',   '2026-02-19', '121M daily active users. Platform engineering. PMX match.'),
  ('Stripe',                'Design Engineer, Expansion',                   'submitted', '$146,400 - $219,600',       'EXCELLENT',   '2026-02-20', 'Web Presence team. stripe.com surfaces. Portfolio required.'),
  ('GitHub',                'Staff Design Engineer',                        'submitted', '$140,400 - $372,300',       'EXCELLENT',   '2026-02-20', 'Visual Comm degree EXPLICITLY WANTED. Copilot company.'),
  ('Ashby',                 'Senior Software Engineer, Product Engineering','submitted', '$153,000 - $220,000',       'EXCELLENT',   '2026-02-20', 'Minimal meetings (<2h/week). Engineers own everything.'),
  ('Chromatic',             'Frontend Engineer',                            'submitted', '$145,000 - $184,000',       'EXCELLENT',   '2026-02-20', 'Storybook visual testing platform. React/Next.js/TypeScript.'),
  ('PostHog',               'Product Engineer',                             'submitted', '$199,120 - $217,984',       'EXCELLENT',   '2026-02-20', '$1K paid SuperDay. 2 meeting-free days/week. Open source.'),
  ('WorkOS',                'Software Engineer - Frontend',                 'submitted', '$175,000 - $250,000',       'EXCELLENT',   '2026-02-20', 'Radix UI creators. Second WorkOS application.'),
  ('Euclid Power',          'Staff Software Engineer, Front End',           'submitted', '$180,000 - $230,000',       'EXCELLENT',   '2026-02-20', 'Renewable energy. Staff IC. Frontend architecture ownership.'),
  ('Airbnb',                'Senior Software Engineer, Guest & Host',       'submitted', '$210,000 - $220,000',       'EXCELLENT',   '2026-02-20', '$210K floor. Cities team. Regulatory systems.'),
  ('Smarter Technologies',  'Design Technologist',                          'submitted', '$170,000 - $220,000',       'EXCELLENT',   '2026-02-17', 'AI tools explicitly named YOUR toolkit (Claude Code, Copilot, Cursor, v0)!'),
  ('Cotiviti',              'Lead Frontend Engineer AI',                    'interested','$170,000 - $210,000',       'EXCELLENT',   '2026-02-24', 'VP Andy reached out directly on LinkedIn. Application window March 3.'),
  ('Netflix',               'UI Engineer (L5), Content & Business',        'submitted', '$320,000 - $500,000',       'EXCEPTIONAL', '2026-02-24', 'HIGHEST SALARY SEEN. Hawkins Design System. L5 Senior IC.'),
  ('Microsoft',             'Software Engineer II - Frontend',              'submitted', '$100,600 - $215,400',       'GOOD',        '2026-02-24', 'Microsoft Ads Campaign UI. React/TypeScript. AI tools preferred.'),
  ('Rate (Guaranteed Rate)','Senior Software Engineer',                     'submitted', '$130,000 - $165,000',       'GOOD',        '2026-02-24', 'UI component libraries. Accessibility emphasis. Mortgage domain.'),
  ('GitHub',                'Staff Design Engineer',                        'submitted', '$140,400 - $372,300',       'STRONG',      '2026-03-02', 'Second application. Visual Comm degree explicitly in required qualifications.'),
  ('HubSpot',               'Staff Design Technologist, AI Tools',         'submitted', '$210,000 - $336,000',       'STRONG',      '2026-03-02', 'AI tools for 250+ designers. Copilot Agent Skills story.'),
  ('Rula',                  'Staff Software Engineer, Patient Onboarding',  'submitted', '$200,745 - $248,600',       'GOOD',        '2026-03-02', 'Frontend-heavy. React/TypeScript/Next.js. Storyblok CMS.'),
  ('Perchwell',             'Staff Software Engineer, Front End',           'submitted', '$200,000 - $245,000',       'GOOD',        '2026-03-02', 'Greenfield frontend platform. React/TypeScript. Lux Capital backed.'),
  ('Machinify',             'Staff Frontend Engineer, Web Apps & Platform', 'submitted', '$200,000 - $240,000',       'GOOD',        '2026-03-02', 'Healthcare AI platform. UI system design and architecture.'),
  ('1Password',             'Senior Frontend Developer, Design Systems',    'submitted', '$153,000 - $214,000',       'GOOD',        '2026-03-03', 'Knox component system. $400M ARR. Forbes Cloud 100.'),
  ('Vercel',                'Design Engineer',                              'submitted', '$196,000 - $294,000',       'STRONG',      '2026-03-03', 'Vercel invented the Design Engineer discipline. Visual Comm degree valued.'),
  ('Vercel',                'Site Engineer',                                'submitted', '$196,000 - $294,000',       'GOOD',        '2026-03-03', 'Growth/marketing engineering. LiteAF is near-perfect case study.'),
  ('Gusto',                 'Staff Software Engineer, Marketing Technology','submitted', '$185,000 - $235,000',       'GOOD',        '2026-03-02', 'AI-first culture. React/TypeScript/Next.js. Kent State alumni connection.')
) AS j(company, title, status, salary, match, applied, notes)
ON c.name = j.company;
